### ISSUE TITLE
Use the java-openliberty stack instead of the java-microprofile stack in examples

### ISSUE THREAD

**Issue by scottkurz** [kabanero-io/draft-guide-codewind-guide#9]
The new java-openliberty stack serves as a replacement for the older java-microprofile stack and brings better performance.

I don't know right as I'm writing this what the name of the template string is that appears in Codewind, but we should make the change to that.

**Comment by scottkurz** [comment]
@j-c-berger    FYI..thanks.

**Comment by mingcyu** [comment]
Completed
